// src/routes/+page.svelte
<script lang="ts">
    import HeaderSection from "$lib/components/header-section.svelte";
    import HeroSection from "$lib/components/hero-section.svelte";
    import AboutSection from "$lib/components/about-section.svelte";
    import SkillsSection from "$lib/components/skills-section.svelte";
    import ProjectsSection from "$lib/components/projects-section.svelte";
    import ContactSection from "$lib/components/contact-section.svelte";
    import FooterSection from "$lib/components/footer-section.svelte";
</script>

<HeaderSection />
<HeroSection />
<AboutSection />
<SkillsSection />
<ProjectsSection />
<ContactSection />
<FooterSection />

// src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { HeroSection } from "../components/hero-section";
import { AboutSection } from "../components/about-section";
import { SkillsSectionNew } from "../components/skills-section-new";
import { ProjectsSectionNew } from "../components/projects-section-new";
import { ContactSectionNew } from "../components/contact-section-new";
import { Header } from "@/components/header";

export const Route = createFileRoute("/")({
    component: HomePage,
});

export function HomePage() {
    return (
        <div className="min-h-screen">
            <title>Ozan - Full Stack Developer Portfolio</title>

            <Header />
            <HeroSection />
            <AboutSection />
            <ProjectsSectionNew />
            <SkillsSectionNew />
            <ContactSectionNew />

            {/* Footer */}
            <footer className="border-t px-4 py-8">
                <div className="mx-auto w-full max-w-7xl border-x px-8 md:px-16">
                    <div className="text-muted-foreground text-center text-sm">
                        <p>© 2024 Ozan. All rights reserved.</p>
                    </div>
                </div>
            </footer>
        </div>
    );
}
